#!/bin/sh
set -e

if [ -z "$1" ]; then
    echo "Usage: uno <project-name>"
    exit 1
fi

composer create-project unotechno/starterkit "$1" --no-install --no-scripts --remove-vcs

cd "$1"
php installer/setup.php
